= Conclusion <sec-conclusion>
This work has explored the flight dynamics of unpowered avian landings and shown how the stall and terminal speeds govern landing behaviour. A vertical flight path is required to attain zero speed and, in principle, can be attained from any initial state provided a large enough initial speed.

The optimal control strategy for unpowered landings of representative bird models involves uncharacteristically large velocities and displacements not commonly observed in nature. This work provides evidence to propose that additional constraints are considered by birds while landing, such as minimizing spatial displacements or maintaining visual control. Wing flapping, high-lift devices such as the alula @leeFunctionAlulaAvian2015, or unsteady aerodynamic effects @poletUnsteadyDynamicsRapid2015 may be used to reduce the spatial requirements of landing trajectories that may otherwise be unfeasible.

Ground-landings further constrain the flight trajectories, making unpowered birds unable to achieve zero touchdown speed. This implies that ground-landing birds may have increased fore or hindlimb muscle mass to dissipate the residual energy and brake to zero speed. This requirement could have shaped the evolution of avian morphology, especially in regard to the redistribution of mass between the legs and the wings @heersWingsLegsAvian2015.

Our results also provide new insights into the physics underlying perching behaviour in raptors @kleinheerenbrinkOptimizationAvianPerching2022, providing a more nuanced explanation for the observed swooping behaviour. The chosen flight behaviour minimises a combination of both touchdown speed and the time spent stalled, but with touchdown speed having a greater influence over the swooping behaviour. Swooping allows for the steeper flight paths required for lower touchdown speeds.

Overall, our results provide a physical basis upon which avian landing behaviour can be understood and, although our focus was on birds, these same principles may be used to better understand unpowered landings in other animals @byrnesEcologicalBiomechanicalInsights2011. The results provide new insight into the physical constraints that shaped avian evolution.
