= Introduction <sec-introduction>

Birds can land on a variety of complex, compliant, and moving surfaces @kovacLearningNatureHow2016 @crandellCopingComplianceTakeoff2018 @roderickBirdinspiredDynamicGrasping2021 @whiteheadMallardLandingBehavior2023 @bhagavatulaLandingSwingingPerch2025 and some can even land without flapping their wings @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022. Landing requires transitioning from aerodynamic, speed-dependent forces on the wings to ground reaction forces on the legs. The bird's momentum must be reduced and redirected while maintaining control over body orientation to allow the legs to contact the landing substrate. With fixed-wings, reducing speed while airborne reduces aerodynamic control, but the otherwise large touchdown speeds would require large ground reaction forces to decelerate sufficiently. Successfully navigating these requirements is critical in allowing birds to transition between aerial and terrestrial locomotion, exploiting a wide range of ecological niches and contributing to their evolutionary success. Despite their importance, few studies have explored the flight dynamics governing landing from flight.

A failure to land safely can result in damage to the muscles and bones, or even be fatal @klemBirdInjuriesCause1990 @byrnesEcologicalBiomechanicalInsights2011. Safe landings are still biomechanically demanding, requiring large muscle forces and strains @proviniTransitionWingLeg2014 @konowSeriesElasticShock2015. Any remaining kinetic energy at touchdown must be dissipated, usually through the hindlimb musculoskeletal system, with larger amounts of kinetic energy requiring larger muscles and thicker bones resulting in greater hindlimb mass. This extra mass would negatively impact flight economy and performance @kullbergImpairedPredatorEvasion1997 @mardenMaximumLiftProduction1987, so selective pressures may have acted to reduce the hindlimb mass @heersWingsLegsAvian2015 @shinFastGroundtoairTransition2024. The landing may therefore have shaped the evolution of avian morphology.

While most birds rely on flapping (powered) flight to land, some species, particularly larger ones @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022, are capable of landing without flapping. It is unknown whether unpowered landings are possible for all species and if so why powered landings are preferred over unpowered ones. A powered landing would incur a greater energetic cost than a unpowered one, so understanding why a bird would choose a more energetically costly landing strategy is of considerable interest. Furthermore, unpowered landing manoeuvres are not unique to birds but are pertinent to the locomotion of other flying vertebrates, including some mammals @bahlmanGlidePerformanceAerodynamics2013 @byrnesTakeoffLandingKinetics2008 and reptiles @khandelwalHowBiomechanicsPath2020 @yeatonUndulationEnablesGliding2020, which lack powered, flapping flight altogether.

Some raptors have been observed to perform unpowered landings when perching, with typical trajectories showing deep dives before a glide up to the perch @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022. It has been suggested that this swooping behaviour is due to birds aiming to minimise the distance flown while stalled @kleinheerenbrinkOptimizationAvianPerching2022. This was shown using predictive simulations of perching trajectories which led to closer agreement with the experimental data when minimising the distance flown post-stall compared with minimising the energy cost or time of flight. However, the simulations constrained the flight path to an initial dive and constrained the touchdown speed to match the experimental data, leading to only a subset of the plausible flight trajectories being explored. It is therefore unclear whether these constraints influenced the model's predictions and whether alternative cost functions might better explain this behaviour. A key contribution of the present paper is to test this previously proposed hypothesis on the motivations that govern perch landing trajectories.

There is also significant interest on the landing from an engineering and control perspective, as an aerial vehicle's ability to land in complex environments substantially enhances its capabilities @roderickTouchdownTakeoffInterface2017. Previous work has studied this theoretically @wickenheiserOptimizationPerchingManeuvers2008 @alikhanFlightDynamicsOptimization2013 @venkateswararaoParametricStudyFixedwing2015 and experimentally, developing fixed- @mooreRobustPoststallPerching2014, flapping- @zuffereyHowOrnithoptersCan2022, and morphing-wing vehicles @greatwoodPerchedLandingManoeuvres2017 @wuestAgilePerchingManeuvers2024 capable of precise landings on a perch. While these results provided useful insight into the physics of the problem, they focused on specific applications, which have limited relevance to the behaviour of birds. Developing a simple model to understand the fundamental dynamics of landing can elucidate principles that govern this behaviour across engineered and biological flight.

Here, our aim is to characterise the flight dynamics of landings to gather further physical evidence of how it impacts flight behaviour and may have shaped the evolution of avian morphology. We first develop a model of unpowered avian flight dynamics and analyse the system's behaviour in phase space. Building on this, we develop an optimal control strategy that minimises touchdown kinetic energy. We then perform predictive simulations of the landing with this control strategy and introduce kinematic constraints on the trajectories to assess their effect on touchdown speed. Finally, we apply our model to experimental observations of perching to better understand the how flight dynamics govern this behaviour.
