= Introduction <sec-introduction>

Birds can land on a variety of complex, compliant, and moving surfaces @kovacLearningNatureHow2016 @crandellCopingComplianceTakeoff2018 @roderickBirdinspiredDynamicGrasping2021 @whiteheadMallardLandingBehavior2023 @bhagavatulaLandingSwingingPerch2025 and even do so without flapping their wings @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022. Landing requires transitioning from aerodynamic, speed-dependent forces on the wings to ground reaction forces on the legs. The bird's momentum vector must be reduced and redirected while controlling body orientation to allow the legs to contact the landing substrate. Reducing speed while airborne reduces aerodynamic control, but the otherwise large touchdown speeds would require large ground reaction forces to decelerate sufficiently. Successfully navigating these requirements is critical in allowing birds to transition between aerial and terrestrial locomotion, exploiting a wide range of ecological niches and contributing to their evolutionary success. Despite this, few studies have explored the flight dynamics governing landing from flight.

A failure to land safely can result in damage to the muscles and bones, or even be fatal @klemBirdInjuriesCause1990 @byrnesEcologicalBiomechanicalInsights2011. Safe landings are still biomechanically demanding, requiring large muscle forces and strains @proviniTransitionWingLeg2014 @konowSeriesElasticShock2015. Any remaining kinetic energy at touchdown must be dissipated, usually through the hindlimb musculoskeletal system, with larger amounts of kinetic energy requiring larger muscles and thicker bones resulting in greater hindlimb mass. This extra mass would negatively impact flight economy and performance @kullbergImpairedPredatorEvasion1997 @mardenMaximumLiftProduction1987 and so selective pressures may have acted to reduce it @heersWingsLegsAvian2015 @shinFastGroundtoairTransition2024. The landing may therefore have helped shape the evolution of avian morphology.

In this work we focus primarily on unpowered landings which we define as those for which there is no mechanical energy input through flapping the wings. Unpowered landings are observed in larger birds @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022, for whom flapping is less common @pennycuickMechanicsBirdMigration1969 @ellingtonLimitationsAnimalFlight1991 and also in other vertebrates such as mammals @bahlmanGlidePerformanceAerodynamics2013 @byrnesTakeoffLandingKinetics2008 and reptiles @khandelwalHowBiomechanicsPath2020 @yeatonUndulationEnablesGliding2020 for whom flapping is not used at all. Such landings are thus widely seen in nature, yet little work has been done to understand the underlying mechanics governing this behaviour.

Unpowered landings are also of relevance to the evolution of flight. The arboreal theory of flight evolution posits that flight began unpowered in tree-dwelling animals, allowing them to glide progressively further between branches and down to the ground @ostromBirdFlightHow1979 @norbergEvolutionVertebrateFlight1985 @templinSpectrumAnimalFlight2000. However, little work has aimed to assess the implications of this theory in terms of possible touchdown speeds and whether these are viable for these early fliers @templinSpectrumAnimalFlight2000. Assessing whether safe landing speeds could be achieved with primitive wings - likely limited in their ability to produce aerodynamic force - could help evaluate the feasibility of this evolutionary pathway.

Extant birds may also choose to glide and have been observed to do so during perch landings with typical trajectories showing deep dives before gliding up to the perch @carruthersAutomaticAeroelasticDevices2007 @kleinheerenbrinkOptimizationAvianPerching2022. It has been suggested that this swooping behaviour is due to birds aiming to minimise the distance flown while stalled @kleinheerenbrinkOptimizationAvianPerching2022. This was shown using a forward dynamics model of perching trajectories which led to closer agreement with the experimental data when minimising the distance flown post-stall compared with minimising the energy cost or time of flight. However, the simulations constrained the flight path to an initial dive and constrained the touchdown speed to match the experimental data, leading to only a subset of the plausible flight trajectories being explored. It is therefore unclear whether these constraints influence the models' predictions and if so whether alternative cost functions might better explain this behaviour. A key contribution of the present paper is to test this previously proposed hypothesis on the motivations that govern landing trajectories.

There is also significant interest on the landing from an engineering and control perspective, as an aerial vehicle's ability to land in complex environments substantially enhances its capabilities @roderickTouchdownTakeoffInterface2017. Previous work has studied this theoretically @wickenheiserOptimizationPerchingManeuvers2008 @alikhanFlightDynamicsOptimization2013 @venkateswararaoParametricStudyFixedwing2015 and experimentally developing fixed- @mooreRobustPoststallPerching2014, flapping- @zuffereyHowOrnithoptersCan2022, and morphing-wing vehicles @greatwoodPerchedLandingManoeuvres2017 @wuestAgilePerchingManeuvers2024 capable of precise landing on a perch. While these results have provided useful insight into the physics of the problem, they have focused on specific applications, which have limited relevance to the behaviour of birds. Developing a simple model to understand the fundamental dynamics of landing can elucidate principles that govern this behaviour across engineered and biological flight.

Here, our aim is to characterise the flight dynamics of landings to gather further physical evidence of how it may have shaped the evolution of flight and avian morphology. We first analyse the system's behaviour in phase space to characterise the dynamics of landing trajectories. Building on this, we develop an optimal control strategy that minimises touchdown kinetic energy. We then perform predictive simulations of the landing with this control strategy and introduce kinematic constraints on the trajectories to assess their effect on touchdown speed. Finally, we apply our model to the experimental observations of perching to better understand the flight dynamics governing this behaviour.
